<?php

declare(strict_types=1);

require_once __DIR__ . '/auth.php';

function render_header(string $title = 'Dashboard'): void {
  $user = htmlspecialchars(current_user());
  echo '<!DOCTYPE html>';
  echo '<html lang="fr">';
  echo '<head>';
  echo '  <meta charset="utf-8">';
  echo '  <meta name="viewport" content="width=device-width, initial-scale=1">';
  echo '  <title>' . htmlspecialchars($title) . ' | MARGE Admin</title>';
  echo '  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">';
  echo '  <script src="https://cdn.tailwindcss.com"></script>';
  echo '  <link href="/css/bootstrap.min.css" rel="stylesheet">';
  echo '  <link href="/dashboard/assets/admin.css" rel="stylesheet">';
  echo '</head>';
  echo '<body class="font-outfit bg-slate-100 text-slate-900">';
  echo '  <div class="min-h-screen xl:flex">';
  echo '    <aside class="w-full xl:w-[280px] bg-slate-900 text-slate-200 px-5 py-6">';
  echo '      <div class="mb-6">';
  echo '        <div class="text-xs uppercase tracking-[0.2em] text-slate-400">MARGE</div>';
  echo '        <div class="text-lg font-semibold">Admin</div>';
  echo '      </div>';
  echo '      <nav class="space-y-2">';
  echo '        <a href="/dashboard/index.php" class="ta-nav">';
  echo '          <svg viewBox="0 0 24 24" class="ta-nav-icon"><path d="M3 13h8V3H3v10zm10 8h8V3h-8v18zM3 21h8v-6H3v6z"/></svg>';
  echo '          <span>Vue globale</span>';
  echo '        </a>';
  echo '        <a href="/dashboard/leads/list.php" class="ta-nav">';
  echo '          <svg viewBox="0 0 24 24" class="ta-nav-icon"><path d="M4 4h16v3H4V4zm0 6h16v3H4v-3zm0 6h10v3H4v-3z"/></svg>';
  echo '          <span>Leads</span>';
  echo '        </a>';
  echo '        <a href="/dashboard/kanban.php" class="ta-nav">';
  echo '          <svg viewBox="0 0 24 24" class="ta-nav-icon"><path d="M3 5h8v14H3V5zm10 0h8v6h-8V5zm0 8h8v6h-8v-6z"/></svg>';
  echo '          <span>Pipeline</span>';
  echo '        </a>';
  echo '        <a href="/dashboard/stats/index.php" class="ta-nav">';
  echo '          <svg viewBox="0 0 24 24" class="ta-nav-icon"><path d="M4 20h16v-2H4v2zM6 9h3v7H6V9zm5-4h3v11h-3V5zm5 7h3v4h-3v-4z"/></svg>';
  echo '          <span>Statistiques</span>';
  echo '        </a>';
  echo '        <a href="/dashboard/devis/list.php" class="ta-nav">';
  echo '          <svg viewBox="0 0 24 24" class="ta-nav-icon"><path d="M6 2h9l5 5v15a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2zm8 1v5h5"/></svg>';
  echo '          <span>Devis</span>';
  echo '        </a>';
  echo '        <a href="/dashboard/settings/users.php" class="ta-nav">';
  echo '          <svg viewBox="0 0 24 24" class="ta-nav-icon"><path d="M12 12a4 4 0 1 0-0.001-8.001A4 4 0 0 0 12 12zm0 2c-4.418 0-8 2.239-8 5v3h16v-3c0-2.761-3.582-5-8-5z"/></svg>';
  echo '          <span>Utilisateurs</span>';
  echo '        </a>';
  echo '        <a href="/dashboard/settings/config.php" class="ta-nav">';
  echo '          <svg viewBox="0 0 24 24" class="ta-nav-icon"><path d="M19.14 12.94a7.45 7.45 0 0 0 .05-.94 7.45 7.45 0 0 0-.05-.94l2.03-1.58a.5.5 0 0 0 .12-.64l-1.92-3.32a.5.5 0 0 0-.6-.22l-2.39.96a7.6 7.6 0 0 0-1.63-.94l-.36-2.54A.5.5 0 0 0 13.9 2h-3.8a.5.5 0 0 0-.49.42l-.36 2.54c-.58.23-1.12.54-1.63.94l-2.39-.96a.5.5 0 0 0-.6.22L2.7 8.46a.5.5 0 0 0 .12.64l2.03 1.58c-.03.31-.05.63-.05.94s.02.63.05.94L2.82 14.14a.5.5 0 0 0-.12.64l1.92 3.32c.13.22.4.31.6.22l2.39-.96c.5.4 1.05.71 1.63.94l.36 2.54c.04.24.25.42.49.42h3.8c.24 0 .45-.18.49-.42l.36-2.54c.58-.23 1.12-.54 1.63-.94l2.39.96c.2.09.47 0 .6-.22l1.92-3.32a.5.5 0 0 0-.12-.64l-2.03-1.58zM12 15a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/></svg>';
  echo '          <span>Configuration</span>';
  echo '        </a>';
  if (is_admin()) {
    echo '        <a href="/dashboard/settings/audit.php" class="ta-nav">';
    echo '          <svg viewBox="0 0 24 24" class="ta-nav-icon"><path d="M12 3a9 9 0 1 0 9 9h-2a7 7 0 1 1-7-7V3zm1 4h-2v6l5 3 1-1.732-4-2.268V7z"/></svg>';
    echo '          <span>Historique</span>';
    echo '        </a>';
  }
  echo '      </nav>';
  echo '      <div class="mt-8 p-4 rounded-xl bg-slate-800/60 text-sm">';
  echo '        <div class="text-slate-400">Compte</div>';
  echo '        <div class="font-medium">' . $user . '</div>';
  echo '        <a class="text-teal-300 text-sm" href="/dashboard/logout.php">Se d&eacute;connecter</a>';
  echo '      </div>';
  echo '    </aside>';
  echo '    <div class="flex-1">';
  echo '      <header class="sticky top-0 z-40 bg-white border-b border-slate-200">';
  echo '        <div class="flex flex-col gap-3 px-6 py-4 lg:flex-row lg:items-center lg:justify-between">';
  echo '          <div class="text-lg font-semibold">' . htmlspecialchars($title) . '</div>';
  echo '          <div class="flex items-center gap-3">';
  echo '            <form class="relative" action="/dashboard/leads/list.php" method="get" data-quick-search="1">';
  echo '              <input type="text" name="q" id="quickSearchInput" placeholder="Recherche rapide..." class="ta-input" autocomplete="off" />';
  echo '              <div id="quickSearchLoader" class="hidden absolute right-3 top-2 text-xs text-slate-400">...</div>';
  echo '              <div id="quickSearchResults" class="hidden absolute right-0 mt-2 w-80 bg-white border border-slate-200 rounded-xl shadow-lg z-50"></div>';
  echo '            </form>';
  echo '            <div class="ta-user-chip">' . $user . '</div>';
  echo '          </div>';
  echo '        </div>';
  echo '      </header>';
  echo '      <main class="p-6 max-w-screen-2xl">';
}

function render_footer(): void {
  echo '      </main>';
  echo '    </div>';
  echo '  </div>';
  echo '<script>';
  echo '(() => {';
  echo '  const forms = document.querySelectorAll("form[data-auto-filter]");';
  echo '  forms.forEach(form => {';
  echo '    if (form.hasAttribute("data-ajax-target")) return;';
  echo '    const submitDebounced = (() => {'; 
  echo '      let t;'; 
  echo '      return () => {'; 
  echo '        clearTimeout(t);'; 
  echo '        t = setTimeout(() => form.requestSubmit ? form.requestSubmit() : form.submit(), 300);'; 
  echo '      };'; 
  echo '    })();';
  echo '    const inputs = form.querySelectorAll("input, select");';
  echo '    inputs.forEach(input => {'; 
  echo '      const type = (input.getAttribute("type") || "").toLowerCase();';
  echo '      if (type === "text" || type === "search" || type === "email" || type === "tel") {'; 
  echo '        input.addEventListener("input", submitDebounced);'; 
  echo '      } else {'; 
  echo '        input.addEventListener("change", submitDebounced);'; 
  echo '      }'; 
  echo '    });';
  echo '  });';
  echo '  const quickForm = document.querySelector("form[data-quick-search]");';
  echo '  if (quickForm) {';
  echo '    const input = document.getElementById("quickSearchInput");';
  echo '    const box = document.getElementById("quickSearchResults");';
  echo '    const loader = document.getElementById("quickSearchLoader");';
  echo '    let t;';
  echo '    const run = () => {';
  echo '      const q = (input.value || "").trim();';
  echo '      if (q.length < 2) { box.classList.add("hidden"); return; }';
  echo '      if (loader) loader.classList.remove("hidden");';
  echo '      fetch("/dashboard/leads/quick_search.php?q=" + encodeURIComponent(q))';
  echo '        .then(r => r.json())';
  echo '        .then(data => {';
  echo '          if (!data || !data.items) return;';
  echo '          let html = "<div class=\\"p-3 text-xs text-slate-500\\">" + data.count + " r\u00e9sultats</div>";';
  echo '          if (data.items.length === 0) {';
  echo '            html += "<div class=\\"px-3 pb-3 text-sm text-slate-400\\">Aucun r\u00e9sultat</div>";';
  echo '          } else {';
  echo '            html += "<div class=\\"divide-y divide-slate-100\\">";';
  echo '            data.items.forEach(item => {';
  echo '              html += "<a class=\\"block px-3 py-2 hover:bg-slate-50\\" href=\\"/dashboard/leads/view.php?id=" + item.id + "\\">";';
  echo '              html += "<div class=\\"text-sm font-medium\\">" + item.name + "</div>";';
  echo '              html += "<div class=\\"text-xs text-slate-400\\">" + item.email + "</div>";';
  echo '              html += "</a>";';
  echo '            });';
  echo '            html += "</div>";';
  echo '          }';
  echo '          box.innerHTML = html;';
  echo '          box.classList.remove("hidden");';
  echo '        })';
  echo '        .catch(() => {})';
  echo '        .finally(() => { if (loader) loader.classList.add("hidden"); });';
  echo '    };';
  echo '    input.addEventListener("input", () => { clearTimeout(t); t = setTimeout(run, 250); });';
  echo '    document.addEventListener("click", (e) => { if (!quickForm.contains(e.target)) box.classList.add("hidden"); });';
  echo '  }';
  echo '})();';
  echo '</script>';
  echo '</body>';
  echo '</html>';
}
